name = "MonteCarlo"
uuid = "035e4b83-fad7-4227-83b8-22e0732c0fd7"
authors = ["JingYu Ning <foldfelis@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
