name = "LinearSearch"
uuid = "5da00125-5d9f-4369-a127-aa7d26c58302"
authors = ["Yueh-Hua Tu <a504082002@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
