name = "ChaosGame"
uuid = "931a44e9-36e9-47d4-8bcf-2a7efbb228b4"
authors = ["JingYu Ning <foldfelis@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
